/**
 * Module Interest Rates & Pricing Traps (Charts 53 - 62)
 */

window.LDC_MODULE_RATES = {
  render: function(data) {
    const c = window.LDC_CONFIG.colors;
    const rateRes = data.rate_resolved;
    const formatINR = window.LDC_CONFIG.formatINR;

    // Chart 53: APR Distribution
    new Chart(document.getElementById('chart53'), {
      type: 'bar',
      data: {
        labels: rateRes.map(r => r.cohort),
        datasets: [{
          label: 'Loan Count in APR Tier',
          data: rateRes.map(r => r.loans),
          backgroundColor: c.indigo,
          borderRadius: 4
        }]
      },
      options: { responsive: true, maintainAspectRatio: false, scales: { y: { grid: { color: c.borderSubtle } } } }
    });

    // Chart 54: Contractual APR vs Realized Net Return
    new Chart(document.getElementById('chart54'), {
      type: 'bar',
      data: {
        labels: rateRes.map(r => r.cohort),
        datasets: [
          { label: 'Contractual APR (%)', data: rateRes.map(r => r.avg_apr), backgroundColor: c.cyan },
          { label: 'Realized Net Ann. Return (%)', data: rateRes.map(r => r.ann_net_pct), backgroundColor: c.emerald }
        ]
      },
      options: { responsive: true, maintainAspectRatio: false, scales: { y: { ticks: { callback: v => v + '%' }, grid: { color: c.borderSubtle } } } }
    });

    // Chart 55: Annualized NPA Rate by Interest Rate Tier
    new Chart(document.getElementById('chart55'), {
      type: 'line',
      data: {
        labels: rateRes.map(r => r.cohort),
        datasets: [{
          label: 'Annualized NPA Rate (%)',
          data: rateRes.map(r => r.ann_npa_pct),
          borderColor: c.crimson,
          backgroundColor: c.crimsonGlow,
          fill: true
        }]
      },
      options: { responsive: true, maintainAspectRatio: false, scales: { y: { ticks: { callback: v => v + '%' }, grid: { color: c.borderSubtle } } } }
    });

    // Chart 56: Platform Fee Burden as % of Gross Interest
    new Chart(document.getElementById('chart56'), {
      type: 'bar',
      data: {
        labels: rateRes.map(r => r.cohort),
        datasets: [{
          label: 'Platform Fee % of Gross Interest',
          data: rateRes.map(r => r.interest_received > 0 ? ((r.platform_fee / r.interest_received) * 100).toFixed(1) : 0),
          backgroundColor: c.amber,
          borderRadius: 4
        }]
      },
      options: { responsive: true, maintainAspectRatio: false, scales: { y: { ticks: { callback: v => v + '%' }, grid: { color: c.borderSubtle } } } }
    });

    // Chart 57: Scatter Matrix - APR vs Score
    const scatterLoanSamples = data.loans.slice(0, 350).map(l => ({
      x: l.score,
      y: l.rate,
      status: l.status
    }));
    new Chart(document.getElementById('chart57'), {
      type: 'scatter',
      data: {
        datasets: [
          {
            label: 'Repaid Loans (Closed)',
            data: scatterLoanSamples.filter(l => l.status === 'CLOSED'),
            backgroundColor: c.emerald,
            pointRadius: 4
          },
          {
            label: 'Defaulted Loans (NPA)',
            data: scatterLoanSamples.filter(l => l.status === 'NPA'),
            backgroundColor: c.crimson,
            pointRadius: 6
          }
        ]
      },
      options: {
        responsive: true,
        maintainAspectRatio: false,
        scales: {
          x: { title: { display: true, text: 'LenDenClub Score' }, grid: { color: c.borderSubtle } },
          y: { title: { display: true, text: 'Contractual APR (%)' }, grid: { color: c.borderSubtle } }
        }
      }
    });

    // Chart 58: Capital Disbursed by APR Tier (₹)
    new Chart(document.getElementById('chart58'), {
      type: 'bar',
      data: {
        labels: rateRes.map(r => r.cohort),
        datasets: [{
          label: 'Disbursed (₹)',
          data: rateRes.map(r => r.disbursed),
          backgroundColor: c.cyan,
          borderRadius: 4
        }]
      },
      options: { responsive: true, maintainAspectRatio: false, scales: { y: { ticks: { callback: v => formatINR(v) }, grid: { color: c.borderSubtle } } } }
    });

    // Chart 59: Net Profit Generated by APR Tier (₹)
    new Chart(document.getElementById('chart59'), {
      type: 'bar',
      data: {
        labels: rateRes.map(r => r.cohort),
        datasets: [{
          label: 'Net Profit (₹)',
          data: rateRes.map(r => r.net_profit),
          backgroundColor: rateRes.map(r => r.net_profit > 0 ? c.emerald : c.crimson),
          borderRadius: 4
        }]
      },
      options: { responsive: true, maintainAspectRatio: false, scales: { y: { ticks: { callback: v => formatINR(v) }, grid: { color: c.borderSubtle } } } }
    });

    // Chart 60: Rupee NPA Loss by APR Tier (₹)
    new Chart(document.getElementById('chart60'), {
      type: 'bar',
      data: {
        labels: rateRes.map(r => r.cohort),
        datasets: [{
          label: 'NPA Loss (₹)',
          data: rateRes.map(r => r.npa_amount),
          backgroundColor: c.crimson,
          borderRadius: 4
        }]
      },
      options: { responsive: true, maintainAspectRatio: false, scales: { y: { ticks: { callback: v => formatINR(v) }, grid: { color: c.borderSubtle } } } }
    });

    // Chart 61: Effective Yield Spread (APR minus Fee minus Ann NPA)
    new Chart(document.getElementById('chart61'), {
      type: 'line',
      data: {
        labels: rateRes.map(r => r.cohort),
        datasets: [{
          label: 'Effective Realized Spread (%)',
          data: rateRes.map(r => (r.avg_apr - r.ann_fee_pct - r.ann_npa_pct).toFixed(1)),
          borderColor: c.emerald,
          backgroundColor: c.emeraldGlow,
          fill: true
        }]
      },
      options: { responsive: true, maintainAspectRatio: false, scales: { y: { ticks: { callback: v => v + '%' }, grid: { color: c.borderSubtle } } } }
    });

    // Chart 62: Risk-Adjusted Pricing Efficiency Ratio
    new Chart(document.getElementById('chart62'), {
      type: 'bar',
      data: {
        labels: rateRes.map(r => r.cohort),
        datasets: [{
          label: 'Efficiency Ratio (Net Return / Ann NPA)',
          data: rateRes.map(r => r.ann_npa_pct > 0 ? (r.ann_net_pct / r.ann_npa_pct).toFixed(2) : 0),
          backgroundColor: rateRes.map(r => r.ann_net_pct > 15 ? c.emerald : (r.ann_net_pct > 0 ? c.amber : c.crimson)),
          borderRadius: 4
        }]
      },
      options: { responsive: true, maintainAspectRatio: false, scales: { y: { grid: { color: c.borderSubtle } } } }
    });
  }
};
